# Generated by Django 3.2.10 on 2021-12-10 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0003_userinformation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinformation',
            old_name='name',
            new_name='org_name',
        ),
    ]
